# Generated by Django 5.1 on 2024-09-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='single_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sb_title', models.CharField(max_length=300)),
                ('sb_image', models.ImageField(default='catalog/01.jpg', upload_to='')),
                ('sb_price', models.IntegerField(default=0)),
                ('sb_description', models.CharField(max_length=500)),
                ('sb_slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
