# Generated by Django 5.1 on 2024-09-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single_blog',
            name='sb_price',
        ),
    ]
