# Generated by Django 5.1 on 2024-12-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_articlecategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='text',
            field=models.TextField(default='نظر', verbose_name='متن نظر'),
        ),
    ]
