# Generated by Django 5.1 on 2025-01-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_articlecomment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نم خانوادگی'),
        ),
    ]
