# Generated by Django 5.1 on 2024-12-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_moduel', '0002_alter_footerlink_footer_link_box_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerlink',
            old_name='title',
            new_name='Ftitle',
        ),
    ]
