# Generated by Django 5.1 on 2024-10-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_moduels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300, verbose_name='عنوان عکس')),
                ('description', models.CharField(max_length=500, verbose_name='توضیح عکس')),
                ('image_adress', models.ImageField(default='media/aks/01.jpg', upload_to='', verbose_name='تصویر دریافتی')),
            ],
            options={
                'verbose_name': 'تصویر دریافتی',
                'verbose_name_plural': 'لیست تصویرهای دریافتی',
            },
        ),
    ]
