# Generated by Django 5.1 on 2024-11-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_moduels', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='contact',
            name='image_adress',
            field=models.ImageField(default='media/aks/01.jpg', upload_to='', verbose_name='تصویر دریافتی'),
        ),
    ]
