# Generated by Django 5.1 on 2024-11-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_moduels', '0003_delete_image_contact_image_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.FileField(upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='image_adress',
        ),
    ]
