# Generated by Django 5.1 on 2024-12-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_alter_user_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_user',
            field=models.TextField(blank=True, null=True, verbose_name='درباره من'),
        ),
    ]
