# Generated by Django 5.1 on 2024-12-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0009_alter_user_about_user_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/profile', verbose_name='تصویر کاربر'),
        ),
    ]
