# Generated by Django 5.1 on 2024-12-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_user',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='درباره من'),
        ),
    ]
