# Generated by Django 5.1 on 2024-12-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0011_alter_user_about_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about_user',
        ),
    ]
