# Generated by Django 5.1 on 2024-12-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0012_remove_user_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/profile', verbose_name='تصویر کاربر'),
        ),
    ]
