# Generated by Django 5.1 on 2024-12-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0018_user_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس دوم'),
        ),
        migrations.AddField(
            model_name='user',
            name='address3',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس سوم'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_org',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس اصلی'),
        ),
    ]
