# Generated by Django 5.1 on 2025-01-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0019_remove_user_address_user_address2_user_address3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address4',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس چهارم'),
        ),
        migrations.AddField(
            model_name='user',
            name='address5',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس پنجم'),
        ),
        migrations.AddField(
            model_name='user',
            name='address6',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس ششم'),
        ),
    ]
