# Generated by Django 5.1 on 2024-10-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ctitle', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('urltitle', models.CharField(db_index=True, max_length=300, verbose_name='عنوان در url')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف / حذف نشده')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=200, verbose_name='عنوان تگ')),
            ],
            options={
                'verbose_name': 'کپشن',
                'verbose_name_plural': 'مدیریت کپشن ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ptitle', models.CharField(db_index=True, max_length=300, verbose_name='عنوان محصول')),
                ('Pprice', models.IntegerField(db_index=True, default=0, verbose_name='قیمت')),
                ('short_description', models.CharField(db_index=True, max_length=360, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(null=True, verbose_name='توضیحات محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف / حذف نشده')),
                ('Pimage', models.ImageField(default='media/aks/01.jpg', upload_to='', verbose_name='تصویر')),
                ('slug', models.SlugField(blank=True, default='')),
                ('Pcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory', verbose_name='دسته بندی')),
                ('product_tag', models.ManyToManyField(to='products.producttag', verbose_name='تگ های محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
