# Generated by Django 5.1 on 2024-12-23 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentcomment', to='products.productcomment', verbose_name='والد'),
        ),
    ]
