# Generated by Django 5.1 on 2025-01-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نم خانوادگی'),
        ),
    ]
