# Generated by Django 5.1 on 2025-01-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
