# Generated by Django 5.1 on 2025-01-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Pcategory',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.productcategory', verbose_name='دسته بندی'),
        ),
    ]
