# Generated by Django 5.1 on 2025-02-02 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_pcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductBrand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productbrand', to='products.productbrand', verbose_name='برند محصول'),
        ),
    ]
